### ISSUE TITLE
Sometimes goes to neighbor rather than parent

### ISSUE THREAD

**Issue by willghatch** [noctuid/evil-textobj-anyblock#1]
Cool plugin!  Sometimes it makes the region fill a neigboring s-exp rather than the parent.  Here is a simple example:

```
([foo b«a»r]
 [baz aoeu])
```

Here the « and » represent the bounds of the region.  If I hit `ib` once, it fills like so:

```
([«foo bar»]
 [baz aoeu])
```

But hitting `ib` again gives me this:

```
([«foo bar]
 [baz aoeu»])
```

When I expect this:

```
(«[foo bar]
 [baz aoeu]»)
```

It behaves similarely with `ab`.  This is assuming the suggested configuration of `b` as the object key, and the default delimiter list.

**Comment by noctuid** [comment]
Yeah, strange things can happen currently when repeating. I don't have any explicit code to allow for repeating, evil just does this for all text objects (you can keep doing `i(` for example). I'll look into this; hopefully its an easy fix.

**Comment by noctuid** [comment]
Actually it was something a lot simpler. This only happened when the inner blocks were square brackets. I forgot to unescape `[` from when I was using `re-search-forward`, but actually I am using `re-search-forward` again... Anyway, thanks for making this issue or I might not have noticed for a while.

If you find any examples of weird behaviour, make a new issue. This particular problem should be fixed.
