### ISSUE TITLE
[Feature Request] Add option for only going to next textobj, ignoring surrounding

### ISSUE THREAD

**Issue by dieggsy** [noctuid/evil-textobj-anyblock#10]
This could be useful in say lisp, javascript, etc. where "ci(" and the like already exist to grab the surrounding text object. It would be cool to have to option to always ignore the surrounding one and go to the next, if there is one.

**Comment by noctuid** [comment]
Thanks for the suggestion and pull request, but I am deprecating this package in favor of [targets.el](https://github.com/noctuid/targets.el) as soon as I can work on it a bit more and fix its more important problems. Targets (already) provides a more generic concept of "composite" text objects that allow you to have as many "anyblock"-style text objects as you like and also creates "next" text objects.

**Comment by dieggsy** [comment]
Ah, neat - I didn't know about that. Thanks! A note about this at the top of the README wouldn't hurt. :)
