### ISSUE TITLE
Evil Textobj-anyblock not listed on MELPA?

### ISSUE THREAD

**Issue by ReneFroger** [noctuid/evil-textobj-anyblock#2]
Hi Lit, thanks for sharing this package! It's appreciated.

However, I couldn't find it on MELPA. Could this perhaps be listed on MELPA?

Thanks in advance!

**Comment by noctuid** [comment]
It is on MELPA (see milkypostman/melpa#3072) as `evil-textobj-anyblock`. I'll add a melpa badge here in the readme as well.

**Comment by ReneFroger** [comment]
Well, sorry. But I can't find it in the latest MELPA list. Perhaps the list from MELPA is not synced with the server.

**Comment by noctuid** [comment]
If you're looking in `list-packages`, you may not find it if you're searching something like "anyblock" (since the name may cut off before the end). Have you tried using `package-install`?

**Comment by ReneFroger** [comment]
Yes, I did. Without any result. I see on the Melpa pull request it's pulled, but I can't find your package with `package-install`.

**Comment by noctuid** [comment]
What about a manual `package-refresh-contents`? `list-packages` (without an arg) should normally refresh when starting. If `package-menu-refresh` doesn't work, then there is something really strange happening. It could maybe be a bug with package.el. I hope you can get it working.

**Comment by ReneFroger** [comment]
That `package-refresh-contents` did the job. Thanks for that! And sorry for any inconvenience.
