### ISSUE TITLE
Why is he not editing until the parenthese?

### ISSUE THREAD

**Issue by ReneFroger** [noctuid/evil-textobj-anyblock#4]
I could be wrong somewhere, I have read the documentation but I got no hint where I went wrong.

This is my configuration for evil-textobj-anyblock:

```
(define-key evil-inner-text-objects-map "b" 'evil-textobj-anyblock-inner-block)
(define-key evil-outer-text-objects-map "b" 'evil-textobj-anyblock-a-block)
(define-key evil-motion-state-map "b" 'evil-textobj-anyblock-forward-open-block-start)
```

For example, I have the following snippet:

```
(evil-define-key 'normal foobar-mode-map (kbd "<RET>") '[] foobar)  
;; ----------------------------------------------------------------------------
;; Some text (06-05-2015).
;; ----------------------------------------------------------------------------       
```

`[]` stands for the cursor. 

I do <kbd>ctb</kbd>. Then he goes to the date, instead ending on the closing parenthese `)` before `foobar`. Perhaps you could tell me why he didn't stop on the closing snippet?

**Comment by noctuid** [comment]
This is because `evil-textobj-anyblock-forward-open-block-start` will go to the next "open block" (e.g. `[`, `(`, `<`, etc.). I can add motions that will go to either the next open or next close block if you want (that will go to the closest `(` or `)` for example).

**Comment by ReneFroger** [comment]
Thanks for your reply. Now I understand it, it would be a pleasure if you could add that motion!

**Comment by noctuid** [comment]
Alright, now you can do the following:

```
(define-key evil-motion-state-map "b" 'evil-textobj-anyblock-forward-any-block-start)
```

**Comment by ReneFroger** [comment]
Thanks for your help. I'm not sure if it ever worked, it was added to my setup the previous month. But I noticed another behaviour than I was initially expecting. This is my configuration for `evil-textobj-anyblock`: 

```
(use-package evil-textobj-anyblock
:defer 3
:config

(define-key evil-inner-text-objects-map "b" 'evil-textobj-anyblock-inner-block)
(define-key evil-outer-text-objects-map "b" 'evil-textobj-anyblock-a-block)
(define-key evil-motion-state-map "b" 'evil-textobj-anyblock-forward-open-block-start)

;; Use dtb
(evil-define-motion my-evil-motion-t (count char)
    "Move before the next COUNT'th occurrence of CHAR."
    :jump t
    :type inclusive
    (interactive "<c><C>")
    (if (= char (string-to-char "b"))
        (evil-textobj-anyblock-forward-open-block-start count)
    (unwind-protect
        (progn
            (evil-find-char count char)
            (if (> (or count 1) 0)
                (backward-char)
            (forward-char)))
        (setcar evil-last-find #'evil-find-char-to))))

(define-key evil-motion-state-map "t" 'my-evil-motion-t)
)
```

This is my configuration.

For example, you have the following:

```
(foo [] bar)
(foo bar)
```

`[]` is the cursor.
When I do <kbd>ctb</kbd>, I get the following:

```
(foo []foo bar)
```

While I was expecting this:

```
(foo [])
(foo bar)
```

Perhaps I'm mistaken and is this by default of Evil-textobj-anyblock. If so, is there any chance to let behave it like above?

**Comment by noctuid** [comment]
@ReneFroger
`evil-textobj-anyblock-forward-open-block-start` needs to be replaced with `evil-textobj-anyblock-forward-any-block-start` (you might want to also change your "b" binding). Also, from your example, I noticed that things don't behave the same with the `my-evil-motion-t` command (it will go one character too far), so it needs a slight alteration. Try this:

```
(evil-define-motion my-evil-motion-t (count char)
  "Move before the next COUNT'th occurrence of CHAR."
  :jump t
  :type inclusive
  (interactive "<c><C>")
  (if (= char (string-to-char "b"))
      (progn
        (evil-textobj-anyblock-forward-any-block-start count)
        (left-char))
    (unwind-protect
        (progn
          (evil-find-char count char)
          (if (> (or count 1) 0)
              (backward-char)
            (forward-char)))
      (setcar evil-last-find #'evil-find-char-to))))
```

Hope that helps.

**Comment by ReneFroger** [comment]
I see, I missed the part about `any` instead `forward`. And I also noticed that will go one character too far, but it was not a huge problem.

After applying your settings, everything is working like I was expecting. :+1: Many, many thanks for your awesome support!
