### ISSUE TITLE
last update not working

### ISSUE THREAD

**Issue by Dickby** [noctuid/evil-textobj-anyblock#7]
evi-textobj-anyblock is bound to 'n' on my system.
in following line | is the cursor:
(fo|o) (bar)
'cin' changes the bar not the foo.

**Comment by noctuid** [comment]
It should be fixed now; let me know if you encounter any problems. Sorry about that. I'm going to try to add tests when I get the chance to prevent future breakage like this.

**Comment by Dickby** [comment]
Works fine now!
Thanks
